# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-12 11:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_auto_20170312_1636'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MainMain',
        ),
    ]
